version: "3.9"

services:
  postgres:
    container_name: website-postgres-local
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_DB: selab2
      POSTGRES_USER: selab2
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "2002:5432"
    restart: always
