openapi: 3.0.0
info:
  title: Learning Platform API
  version: "1.0"
servers:
  - url: http://localhost:5000

tags:
  - name: Question
    description: Everything about questions
  - name: Assignment
    description: Everything about assignments
  - name: Authentication
    description: Everything about authentication
  - name: Learning object
    description: Everything about learning objects
  - name: Selfmade learning object
    description: Everything about learning objects created by teachers
  - name: Learning path
    description: Everything about learning paths
  - name: Selfmade learning path
    description: Everything about learning paths created by teachers
  - name: Class
    description: Everything about classes
  - name: Invite
    description: Everything about invitations
  - name: Join request
    description: Everything about join requests
  - name: Feedback
    description: Everything about feedback

paths:
  /auth:
    $ref: "./routes/authentication/authenticationRoutes.yaml"
  /class:
    $ref: "./routes/class/classRoutes.yaml"
  /invite:
    $ref: "./routes/invite/inviteRoutes.yaml"
  /join-request:
    $ref: "./routes/joinRequest/joinRequestRoutes.yaml"
  /pathByTeacher:
    $ref: "./routes/teacherMadeLearningPath/pathByTeacherRoutes.yaml"
  /learningPath/:learningPathId/node:
    $ref: "./routes/teacherMadeLearningPath/learningPathNodeRoutes.yaml"
  /learningObjectByTeacher:
    $ref: "./routes/teacherMadeLearningObject/learningObjectByTeacherRoutes.yaml"
  /team:
    $ref: "./routes/team/teamRoutes.yaml"
  /assignment:
    $ref: "./routes/assignment/assignmentRoutes.yaml"
  /feedback:
    post:
      tags:
        - Feedback
      summary: Create feedback for a submission
      description: Create new feedback for a specific submission. Requires teacher authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                submissionId:
                  type: integer
                  description: The ID of the submission
                description:
                  type: string
                  description: The feedback description
      responses:
        "201":
          description: Feedback created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        "401":
          description: Unauthorized access
        "400":
          description: Invalid request body

  /feedback/submission/{submissionId}:
    get:
      tags:
        - Feedback
      summary: Get feedback for a submission
      description: Retrieve feedback associated with a specific submission. Requires teacher authentication.
      parameters:
        - name: submissionId
          in: path
          required: true
          description: The ID of the submission
          schema:
            type: integer
      responses:
        "200":
          description: Feedback for the submission
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        "401":
          description: Unauthorized access
        "404":
          description: Submission not found

    patch:
      tags:
        - Feedback
      summary: Update feedback for a submission
      description: Update the feedback associated with a specific submission. Requires teacher authentication.
      parameters:
        - name: submissionId
          in: path
          required: true
          description: The ID of the submission
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: The updated feedback description
      responses:
        "200":
          description: Feedback updated successfully
        "401":
          description: Unauthorized access
        "404":
          description: Submission not found

    delete:
      tags:
        - Feedback
      summary: Delete feedback for a submission
      description: Delete the feedback associated with a specific submission. Requires teacher authentication.
      parameters:
        - name: submissionId
          in: path
          required: true
          description: The ID of the submission
          schema:
            type: integer
      responses:
        "204":
          description: Feedback deleted successfully
        "401":
          description: Unauthorized access
        "404":
          description: Submission not found

  /feedback/assignment/{assignmentId}/evaluation/{evaluationId}:
    get:
      tags:
        - Feedback
      summary: Get all feedback for an evaluation
      description: Retrieve all feedback associated with a specific evaluation for an assignment. Requires teacher authentication.
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: The ID of the assignment
          schema:
            type: integer
        - name: evaluationId
          in: path
          required: true
          description: The ID of the evaluation
          schema:
            type: string
      responses:
        "200":
          description: A list of feedback for the evaluation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feedback"
        "401":
          description: Unauthorized access
        "404":
          description: Evaluation not found

  /learningObject:
    $ref: "./routes/learningObject/learningObjectRoutes.yaml"
  /learningPath:
    $ref: "./routes/learningPath/learningPathRoutes.yaml"
  /question/{questionId}:
    get:
      tags:
        - Question
      summary: Get a specific question
      description: Allows authorized users to retrieve a specific question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
      responses:
        "200":
          description: Question retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

    patch:
      tags:
        - Question
      summary: Update a question
      description: Allows authorized users to update a specific question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
      responses:
        "200":
          description: Question updated successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

    delete:
      tags:
        - Question
      summary: Delete a question
      description: Allows authorized users to delete a specific question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
      responses:
        "204":
          description: Question deleted successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/{questionId}/message:
    post:
      tags:
        - Question
      summary: Create a message for a question
      description: Allows authorized users to create a message for a specific question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
      responses:
        "201":
          description: Message created successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/{questionId}/message/{questionMessageId}:
    patch:
      tags:
        - Question
      summary: Update a message for a question
      description: Allows authorized users to update a specific message for a question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
        - name: questionMessageId
          in: path
          required: true
          description: The ID of the question message
          schema:
            type: integer
      responses:
        "200":
          description: Message updated successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

    delete:
      tags:
        - Question
      summary: Delete a message for a question
      description: Allows authorized users to delete a specific message for a question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
        - name: questionMessageId
          in: path
          required: true
          description: The ID of the question message
          schema:
            type: integer
      responses:
        "204":
          description: Message deleted successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/{questionId}/messages:
    get:
      tags:
        - Question
      summary: Get messages for a question
      description: Allows authorized users to retrieve all messages for a specific question.
      parameters:
        - name: questionId
          in: path
          required: true
          description: The ID of the question
          schema:
            type: integer
      responses:
        "200":
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QuestionMessage"
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/team/{teamId}/:
    get:
      tags:
        - Question
      summary: Get questions for a team
      description: Allows authorized users to retrieve all questions for a specific team.
      parameters:
        - name: teamId
          in: path
          required: true
          description: The ID of the team
          schema:
            type: integer
      responses:
        "200":
          description: Questions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/class/{classId}:
    get:
      tags:
        - Question
      summary: Get questions for a class
      description: Allows authorized users to retrieve all questions for a specific class.
      parameters:
        - name: classId
          in: path
          required: true
          description: The ID of the class
          schema:
            type: integer
      responses:
        "200":
          description: Questions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/assignment/{assignmentId}/class/{classId}:
    get:
      tags:
        - Question
      summary: Get questions for an assignment in a class
      description: Allows authorized users to retrieve all questions for a specific assignment in a class.
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: The ID of the assignment
          schema:
            type: integer
        - name: classId
          in: path
          required: true
          description: The ID of the class
          schema:
            type: integer
      responses:
        "200":
          description: Questions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/assignment/{assignmentId}/learningPath/{learningPathId}/:
    post:
      tags:
        - Question
      summary: Create a general question for an assignment
      description: Allows a student in a team with an assignment to create a general question.
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: The ID of the assignment
          schema:
            type: integer
        - name: learningPathId
          in: path
          required: true
          description: The ID of the learning path
          schema:
            type: integer
      responses:
        "201":
          description: Question created successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access

  /question/assignment/{assignmentId}/learningPath/{learningPathId}/learningObject/{learningObjectId}/:
    post:
      tags:
        - Question
      summary: Create a specific question for a learning object
      description: Allows a student in a team with an assignment to create a specific question for a learning object.
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: The ID of the assignment
          schema:
            type: integer
        - name: learningPathId
          in: path
          required: true
          description: The ID of the learning path
          schema:
            type: integer
        - name: learningObjectId
          in: path
          required: true
          description: The ID of the learning object
          schema:
            type: integer
      responses:
        "201":
          description: Question created successfully
        "401":
          description: Unauthorized access
        "403":
          description: Forbidden access
  /progress:
    $ref: "./routes/progress/progressRoutes.yaml"
  /submission:
    $ref: "./routes/submission/submissionRoutes.yaml"

components:
  schemas:
    Feedback:
      type: object
      properties:
        submissionId:
          type: integer
          description: The ID of the submission the feedback is for.
        teacherId:
          type: integer
          description: The ID of the teacher providing the feedback.
        description:
          type: string
          description: The feedback provided.

    Question:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the question.
        teamId:
          type: integer
          description: The ID of the team that asked the question.
        title:
          type: string
          description: The title of the question.
        assignmentId:
          type: integer
          description: The ID of the assignment the question is linked to.
        type:
          type: string
          enum:
            - general
            - specific
          description: The type of question. General questions are linked to learning paths. Specific questions are linked to learning objects.
        createdAt:
          type: string
          format: date-time
          description: The date and time the question was created.
        updatedAt:
          type: string
          format: date-time
          description: The date and time the question was last updated.
        questionConversation:
          type: array
          items:
            $ref: "#/components/schemas/QuestionMessage"

    QuestionMessage:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the message.
        questionId:
          type: integer
          description: The ID of the question the message is linked to.
        userId:
          type: integer
          description: The ID of the user who posted the message.
        text:
          type: string
          description: The content of the message.
        createdAt:
          type: string
          format: date-time
          description: The date and time the message was created.
        updatedAt:
          type: string
          format: date-time
          description: The date and time the message was last updated.
