name: Deploy Server

on:
  push:
    branches: [prisma-schema-celeste]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd /home/selab2/Dwengo-4/dwengo_backend
          killall node
          npx nodemon server.js > /dev/null 2>&1 &
          echo "Deployment completed successfully"
