name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test-develop:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run integration tests
        run: |
          cd /home/selab2/Dwengo-4/dwengo_backend
          git pull
          git checkout develop
          npm ci
          npm run test:int

  test-automated:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run integration tests
        run: |
          cd /home/selab2/Dwengo-4/dwengo_backend
          git stash
          git checkout develop
          git stash
          git pull
          npm ci
          npm run test:int

  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Kill existing Node processes
        run: pkill -f "node.*server.ts" || true

      - name: Deploy branch
        run: |
          cd /home/selab2/Dwengo-4/
          git checkout main
          git stash
          git pull
          git stash
          cd /home/selab2/Dwengo-4/frontend
          npm i
          npm run build
          cd /home/selab2/Dwengo-4/dwengo_backend
          npm i
          PORT=4000 npx nodemon server.ts > /dev/null 2>&1 &
          sleep 3
          echo "Branch deployment completed successfully on port $PORT"
