name: Deploy Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd /home/selab2/Dwengo-4/dwengo_backend
          sudo sudo npx nodemon server.js

          echo "Deployment completed successfully"
