name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - yolo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Kill existing Node processes
        run: pkill -f "node.*server.js" || true

      - name: Deploy main branch
        run: |
          cd /home/selab2/Dwengo-4/
          git pull
          git checkout main
          cd /home/selab2/Dwengo-4/dwengo_backend/
          PORT=3000 npx nodemon server.js > /dev/null 2>&1 &
          sleep 3 #aapjes
          echo "Main branch deployment completed successfully on port $PORT"
