name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - yolo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Kill existing Node processes
        run: killall node || true

      - name: Deploy main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          PORT: 3000
        run: |
          cd /home/selab2/Dwengo-4/
          git pull
          cd dwengo_backend
          PORT=$PORT npx nodemon server.js > /dev/null 2>&1 &
          echo "Main branch deployment completed successfully on port $PORT"

      - name: Deploy yolo branch
        if: ${{ github.ref == 'refs/heads/yolo' }}
        env:
          PORT: 4000
        run: |
          cd /home/selab2/Dwengo-4-yolo/Dwengo-4/
          git pull
          cd dwengo_backend
          PORT=$PORT npx nodemon server.js > /dev/null 2>&1 &
          echo "Yolo branch deployment completed successfully on port $PORT"
